### ISSUE TITLE
Improve pack color distribution

### ISSUE THREAD

**Issue by scottchiefbaker** [danieljbrooks/draftsim-launch#3]
Do we know how Wizards handles color distribution in a pack? Right now it seems the packs are semi-random in terms of color distribution? I just got a pack that had six white cards in it, and no red cards.

**Comment by danieljbrooks** [comment]
The model currently randomly generates cards, which can lead to some packs with many cards of one color. Information on magic origins print runs is available here:

https://www.reddit.com/r/lrcast/comments/3dkr40/magic_origins_anatomy_of_a_booster_pack_common/

The simplest solution is probably to fix the number of cards per color between 1 and 3.

There has also been demand for making repeat rares less likely, because print runs apparently make repeat rares less likely in sealed boxes.

**Comment by danieljbrooks** [comment]
Implemented 1-3 commons per pack. Random numbers used for uncommons/rares like MTGO. Closed.
